monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "bluez_card.7C_58_CA_00_1C_85"
      }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp-sink ]
        bluez5.connect-profile = [ a2dp-sink ]
      }
    }
  }
]