# taken form https://github.com~/.config/desktop/background/basecamp/omarchy/blob/master/default/hypr/autostart.conf

#exec-once = uwsm-app -- fcitx5
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- walker --gapplication-service
