# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

env = GDK_SCALE,1.125
monitor=,preferred,auto,auto

# Laptop monitor
#monitor = desc:Lenovo Group Limited ATNA40HQ02-0, 2880x1800@120, auto, 1.25
monitorv2 {
  output = desc:Lenovo Group Limited ATNA40HQ02-0
  mode = 2880x1800@120
  position = auto
  scale = 1.25
  cm = dcip3
}

# External monitor
monitorv2 {
  output = desc:ASUSTek COMPUTER INC PG32UCDP SALMQS120245
  mode = 3840x2160@120
  position = auto-right
  scale = 1
  vrr = 2
  bitdepth = 10
  cm = dcip3
}
